### ISSUE TITLE
No module named base_service

### ISSUE THREAD

**Issue by chiedojohn** [markfinger/django-react#29]
Hey there,
I'm getting the error ```No module named base_service```

Error at line 4: ```from django_node.base_service import BaseService``` in django-react/django_react/services/__init__.py

It looks like base_service is no longer part of the django_node package.

Any ideas?

Thanks,

**Comment by mic159** [comment]
Sounds like you installed django-node from pypi, not from github.
You need to ensure you installed `django-node` from github before you install `django-react` like this:
```
pip install -e git+https://github.com/markfinger/django-node.git#egg=django-node
pip install -e git+https://github.com/markfinger/django-react.git#egg=django-react
```
Otherwise django-node will trigger a download from pypi, which is out of date.

@markfinger, maybe you could include a minimum version number in the requirements so that it will fail to install using the pypi version?

**Comment by chiedojohn** [comment]
Hey,
I am pretty sure I did the above as I was following the readme.

I checked out the source here though https://github.com/markfinger/django-react/tree/master/django_react/services

I'm not seeing the base_service package there. You sure the django-react repo doesn't need to be updated?

Sorry if the mistake is on my end.

Thanks!

**Comment by mic159** [comment]
Its complaining about `django-node` not `django-react`.
The module is here: https://github.com/markfinger/django-node/blob/master/django_node/base_service.py

**Comment by markfinger** [comment]
I actually managed to replicate the problem. If I pip installed from the then latest commit, it overrode the django-node version and rolled it back to the latest from pypi - which had an incompatible API.

Anyway, the codebases have stabilised for the moment, so I've gone through and updated PyPI with the latest codebases for everything. So you can now `pip install django-react` and everything should work fine.

Thanks for reporting the issue, Chiedo, and thanks for trying to fix it, Michael! :balloon:

**Comment by chiedojohn** [comment]
Thanks Mark,
I was actually about to let you know that this morning so I'm glad to replicated the problem also on your end!

Thanks for your help also Michael!
