### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by zubair812** [markfinger/django-react#34]
Hi Mark,
Just clone this repo and I am getting a type error as follwoing for both "translate and bundle":

render_component() got an unexpected keyword argument 'translate'

What I am doing wrong :(

**Comment by markfinger** [comment]
If you installed from PyPI, the codebase will have some features missing. The docs at https://github.com/markfinger/django-react/tree/0.10.0 will give you a clearer idea of the API.

If you pull straight from the repo, it should be fine.

If the following produces an import error, you're probably running v0.10
```python
from django_react.bundle import bundle_component
```

I'll push a new stable release sometime today or tomorrow.
